# Generated by Django 3.1.1 on 2020-09-22 12:31

import book.models
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genre', '0001_initial'),
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view', models.CharField(max_length=100)),
                ('upvote', models.CharField(max_length=100)),
                ('downvote', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=254)),
                ('book_cover_url', models.ImageField(upload_to='')),
                ('view', models.CharField(max_length=100)),
                ('published_time', models.DateField(auto_now=True)),
                ('user_count', models.CharField(max_length=100)),
                ('ranking', models.CharField(max_length=100)),
                ('book_brief_info', models.CharField(max_length=100)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='author.author')),
                ('book_details', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.bookdetails')),
                ('genre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='genre.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_no', models.PositiveIntegerField(blank=True, null=True)),
                ('chapter_name', models.CharField(max_length=100)),
                ('chapter_url', models.FileField(upload_to='')),
                ('state', enumchoicefield.fields.EnumChoiceField(default=book.models.State(3), enum_class=book.models.State, max_length=8)),
                ('book_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.books')),
            ],
        ),
    ]
