# Generated by Django 3.1.1 on 2020-11-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=500)),
                ('genre_img', models.ImageField(default='static/genre/young-user-icon.png', upload_to='static/genre')),
            ],
        ),
    ]
