# Generated by Django 3.1.1 on 2020-11-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre_img',
            field=models.ImageField(default='', upload_to='static/genre'),
        ),
    ]
