# Generated by Django 3.1.1 on 2020-10-01 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '__first__'),
        ('usercollection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercollection',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userprofile.userprofile'),
            preserve_default=False,
        ),
    ]
